controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# config/routes.yaml

pagina_principal:
    path: /
    controller: App\Controller\ProductController::paginaPrincipal

agregar_al_carrito:
    path: '/agregar/{id}'
    controller: 'App\Controller\ProductController::agregarAlCarrito'
    methods: ['GET']  
    
detalle_producto:
    path: /producto/{id}
    controller: App\Controller\ProductController::detalleProducto
    requirements:
        id: '\d+'

carrito_compras:
    path: /carrito
    controller: App\Controller\ProductController::carritoCompras
